theme: jekyll-theme-minimal
title: Igino's homepage
description: Bookmark this to keep an eye on my project updates!
include: [".well-known"]

defaults:
  - scope:
      path: ".well-known/appspecific"
    values:
      layout: null
